# Generated by Django 5.2.6 on 2025-12-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp_var_22', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=200, verbose_name='Издательство'),
        ),
    ]
