# Generated by Django 5.2.6 on 2025-10-08 10:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp_var_22', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена на момент покупки'),
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp_var_22.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp_var_22.book')),
            ],
            options={
                'verbose_name': 'Автор книги',
                'verbose_name_plural': 'Авторы книги',
                'unique_together': {('book', 'author')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='books', through='firstapp_var_22.BookAuthor', to='firstapp_var_22.author', verbose_name='Автор(ы)'),
        ),
    ]
