# Generated by Django 5.2.6 on 2025-12-13 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp_var_22', '0004_alter_review_unique_together_remove_book_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp_var_22.category')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp_var_22.customer')),
            ],
        ),
    ]
